services:
  - type: web
    name: post-app-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: PORT
        value: 3000
