/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type PostCategory = typeof PostCategory[keyof typeof PostCategory];


export const PostCategory = {
  yellow: 'yellow',
  green: 'green',
  red: 'red',
  blue: 'blue',
} as const;

export interface PostResponse {
  id: number;
  userId: string;
  username: string;
  content?: string | null;
  imageUrl?: string | null;
  category: PostCategory;
  likesCount: number;
  commentsCount: number;
  savesCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface ListPostsResponse {
  posts: PostResponse[];
  total: number;
}

export interface CreatePostBody {
  username: string;
  content?: string | null;
  imageUrl?: string | null;
  category: PostCategory;
}

export interface LikeBody {
  userId: string;
}

export interface LikeResponse {
  liked: boolean;
  likesCount: number;
}

export interface SaveBody {
  userId: string;
}

export interface SaveResponse {
  saved: boolean;
  savesCount: number;
}

export interface AddCommentBody {
  userId: string;
  username: string;
  content: string;
}

export interface CommentResponse {
  id: number;
  postId: number;
  userId: string;
  username: string;
  content: string;
  createdAt: string;
}

export interface ListCommentsResponse {
  comments: CommentResponse[];
}

export type ListPostsParams = {
category?: ListPostsCategory;
limit?: number;
offset?: number;
};

export type ListPostsCategory = typeof ListPostsCategory[keyof typeof ListPostsCategory];


export const ListPostsCategory = {
  yellow: 'yellow',
  green: 'green',
  red: 'red',
  blue: 'blue',
} as const;

