/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddCommentBody,
  CommentResponse,
  CreatePostBody,
  HealthStatus,
  LikeBody,
  LikeResponse,
  ListCommentsResponse,
  ListPostsParams,
  ListPostsResponse,
  PostResponse,
  SaveBody,
  SaveResponse
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType, BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListPostsUrl = (params?: ListPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/posts?${stringifiedParams}` : `/api/posts`
}

/**
 * @summary List all posts
 */
export const listPosts = async (params?: ListPostsParams, options?: RequestInit): Promise<ListPostsResponse> => {

  return customFetch<ListPostsResponse>(getListPostsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPostsQueryKey = (params?: ListPostsParams,) => {
    return [
    `/api/posts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPostsQueryOptions = <TData = Awaited<ReturnType<typeof listPosts>>, TError = ErrorType<unknown>>(params?: ListPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPosts>>> = ({ signal }) => listPosts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPostsQueryResult = NonNullable<Awaited<ReturnType<typeof listPosts>>>
export type ListPostsQueryError = ErrorType<unknown>


/**
 * @summary List all posts
 */

export function useListPosts<TData = Awaited<ReturnType<typeof listPosts>>, TError = ErrorType<unknown>>(
 params?: ListPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPostsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreatePostUrl = () => {




  return `/api/posts`
}

/**
 * @summary Create a new post
 */
export const createPost = async (createPostBody: CreatePostBody, options?: RequestInit): Promise<PostResponse> => {

  return customFetch<PostResponse>(getCreatePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPostBody)
  }
);}




export const getCreatePostMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<CreatePostBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<CreatePostBody>}, TContext> => {

const mutationKey = ['createPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPost>>, {data: BodyType<CreatePostBody>}> = (props) => {
          const {data} = props ?? {};

          return  createPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createPost>>>
    export type CreatePostMutationBody = BodyType<CreatePostBody>
    export type CreatePostMutationError = ErrorType<void>

    /**
 * @summary Create a new post
 */
export const useCreatePost = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<CreatePostBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPost>>,
        TError,
        {data: BodyType<CreatePostBody>},
        TContext
      > => {
      return useMutation(getCreatePostMutationOptions(options));
    }

export const getGetPostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

/**
 * @summary Get a single post
 */
export const getPost = async (id: number, options?: RequestInit): Promise<PostResponse> => {

  return customFetch<PostResponse>(getGetPostUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPostQueryKey = (id: number,) => {
    return [
    `/api/posts/${id}`
    ] as const;
    }


export const getGetPostQueryOptions = <TData = Awaited<ReturnType<typeof getPost>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPost>>> = ({ signal }) => getPost(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPostQueryResult = NonNullable<Awaited<ReturnType<typeof getPost>>>
export type GetPostQueryError = ErrorType<void>


/**
 * @summary Get a single post
 */

export function useGetPost<TData = Awaited<ReturnType<typeof getPost>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPostQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getDeletePostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

/**
 * @summary Delete a post
 */
export const deletePost = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeletePostUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeletePostMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePost>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePost(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePost>>>

    export type DeletePostMutationError = ErrorType<void>

    /**
 * @summary Delete a post
 */
export const useDeletePost = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePost>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePostMutationOptions(options));
    }

export const getToggleLikeUrl = (id: number,) => {




  return `/api/posts/${id}/like`
}

/**
 * @summary Like or unlike a post
 */
export const toggleLike = async (id: number,
    likeBody: LikeBody, options?: RequestInit): Promise<LikeResponse> => {

  return customFetch<LikeResponse>(getToggleLikeUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(likeBody)
  }
);}




export const getToggleLikeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleLike>>, TError,{id: number;data: BodyType<LikeBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof toggleLike>>, TError,{id: number;data: BodyType<LikeBody>}, TContext> => {

const mutationKey = ['toggleLike'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleLike>>, {id: number;data: BodyType<LikeBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  toggleLike(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToggleLikeMutationResult = NonNullable<Awaited<ReturnType<typeof toggleLike>>>
    export type ToggleLikeMutationBody = BodyType<LikeBody>
    export type ToggleLikeMutationError = ErrorType<unknown>

    /**
 * @summary Like or unlike a post
 */
export const useToggleLike = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleLike>>, TError,{id: number;data: BodyType<LikeBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof toggleLike>>,
        TError,
        {id: number;data: BodyType<LikeBody>},
        TContext
      > => {
      return useMutation(getToggleLikeMutationOptions(options));
    }

export const getToggleSaveUrl = (id: number,) => {




  return `/api/posts/${id}/save`
}

/**
 * @summary Save or unsave a post
 */
export const toggleSave = async (id: number,
    saveBody: SaveBody, options?: RequestInit): Promise<SaveResponse> => {

  return customFetch<SaveResponse>(getToggleSaveUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(saveBody)
  }
);}




export const getToggleSaveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleSave>>, TError,{id: number;data: BodyType<SaveBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof toggleSave>>, TError,{id: number;data: BodyType<SaveBody>}, TContext> => {

const mutationKey = ['toggleSave'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleSave>>, {id: number;data: BodyType<SaveBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  toggleSave(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToggleSaveMutationResult = NonNullable<Awaited<ReturnType<typeof toggleSave>>>
    export type ToggleSaveMutationBody = BodyType<SaveBody>
    export type ToggleSaveMutationError = ErrorType<unknown>

    /**
 * @summary Save or unsave a post
 */
export const useToggleSave = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleSave>>, TError,{id: number;data: BodyType<SaveBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof toggleSave>>,
        TError,
        {id: number;data: BodyType<SaveBody>},
        TContext
      > => {
      return useMutation(getToggleSaveMutationOptions(options));
    }

export const getListCommentsUrl = (id: number,) => {




  return `/api/posts/${id}/comments`
}

/**
 * @summary Get comments for a post
 */
export const listComments = async (id: number, options?: RequestInit): Promise<ListCommentsResponse> => {

  return customFetch<ListCommentsResponse>(getListCommentsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCommentsQueryKey = (id: number,) => {
    return [
    `/api/posts/${id}/comments`
    ] as const;
    }


export const getListCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsQueryError = ErrorType<unknown>


/**
 * @summary Get comments for a post
 */

export function useListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCommentsQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getAddCommentUrl = (id: number,) => {




  return `/api/posts/${id}/comments`
}

/**
 * @summary Add a comment to a post
 */
export const addComment = async (id: number,
    addCommentBody: AddCommentBody, options?: RequestInit): Promise<CommentResponse> => {

  return customFetch<CommentResponse>(getAddCommentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addCommentBody)
  }
);}




export const getAddCommentMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{id: number;data: BodyType<AddCommentBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{id: number;data: BodyType<AddCommentBody>}, TContext> => {

const mutationKey = ['addComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addComment>>, {id: number;data: BodyType<AddCommentBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  addComment(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddCommentMutationResult = NonNullable<Awaited<ReturnType<typeof addComment>>>
    export type AddCommentMutationBody = BodyType<AddCommentBody>
    export type AddCommentMutationError = ErrorType<void>

    /**
 * @summary Add a comment to a post
 */
export const useAddComment = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addComment>>, TError,{id: number;data: BodyType<AddCommentBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addComment>>,
        TError,
        {id: number;data: BodyType<AddCommentBody>},
        TContext
      > => {
      return useMutation(getAddCommentMutationOptions(options));
    }

